name: no_signal
description: A Chatting App using Appwrite as a backend service and Riverpod as
  state management solution.
publish_to: "none" 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  appwrite: ^8.1.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dart_appwrite: ^7.1.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_hex_color: ^2.0.0
  msix: ^3.6.2
  flutter_lints: ^2.0.1
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.4
  introduction_screen: ^3.0.2
  lottie: ^1.1.0
  permission_handler: ^10.0.0
  url_launcher: ^6.0.12
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/lottieassets/

msix_config:
  display_name: YouChat App
  publisher_display_name: You foundation
  identity_name: com.you.chat-app
  msix_version: 1.0.0.0
  capabilities: internetClient, location
  publisher: CN=YouFoundation, O=Msix Testing... 
  sign_msix: false